### ISSUE TITLE
Project incorrectly flagged as bugfix fork

### ISSUE THREAD

**Issue by mattyr** [rubytoolbox/rubytoolbox#405]
https://www.ruby-toolbox.com/projects/sidecloq appears to be incorrectly flagged as a bugfix fork of sidetiq; it is not (I'm the creator).  Reporting per https://www.ruby-toolbox.com/pages/docs/features/bugfix_forks -- let me know if more info is needed!

**Comment by colszowka** [comment]
Hey @mattyr, thanks for reporting this! The culprit is the 100% equal gem description `Recurring jobs for Sidekiq`.

A quick fix you could do would be to simply adjust your gem's description to have different wording, but I'll also investigate expanding the description matching to the gem's other metadata. The assumption for the description equality fork detection is that forked gems rarely see changes to their gemspec metadata, so finding them by description worked well for the gems I inspected. I will look into this in the next week or so.

**Comment by mattyr** [comment]
Thanks, and I can see there certainly is some merit in trying that description-driven approach.

I can alter the description for now; if there's additional info/help I can provide, let me know!

**Comment by colszowka** [comment]
Excellent, thanks @mattyr! Let's leave this issue open though so I don't forget to look more closely into potentially expanding the existing approach into other gem data, your gem likely isn't the only one that will run into this problem

**Comment by colszowka** [comment]
Haven't received any further reports of this in over a year, so I'm just gonna close this one as it generally doesn't seem to be a big issue
