### ISSUE TITLE
Project score computation

### ISSUE THREAD

**Issue by ce-walalang** [rubytoolbox/rubytoolbox#568]
Hi rubytoolbox,

Not urgent and not really an issue just really curious. Hope it's ok to ask why is the project score computed this way? Where did the number 5 came from?

https://github.com/rubytoolbox/rubytoolbox/blob/e3c9c2f90e337cc350b35618e24a8d1d4c2cfaa2/app/jobs/project_score_job.rb#L36

Thank you so much! 🙂

**Comment by colszowka** [comment]
@ce-walalang Sorry for the lag... There's no particular reason to the choice of 5, it's just some number I picked for random reasons back when I built the site in 2009 because it I considered a big amount of forks a good sign that there is an active community interested in contributing to a library, versus maybe a project looking interesting and getting some attention on hackernews / reddit / ruby weekly / wherever and gaining a lot of stars but little actually engaged community

**Comment by ce-walalang** [comment]
no worries @colszowka and thank you. got it. :)
